# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import session_pb2 as session__pb2
import measurement_pb2 as measurement__pb2
import command_pb2 as command__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x07SKF.App\x1a\rsession.proto\x1a\x11measurement.proto\x1a\rcommand.proto\x1a\x0c\x63ommon.proto\"\x8b\x03\n\x03\x41pp\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.SKF.common.Header\x12\x30\n\x0copen_session\x18\n \x01(\x0b\x32\x18.SKF.Session.OpenSessionH\x00\x12\x34\n\x0e\x61\x63\x63\x65pt_session\x18\x0b \x01(\x0b\x32\x1a.SKF.Session.AcceptSessionH\x00\x12\x42\n\x13measurement_request\x18\x0c \x01(\x0b\x32#.SKF.Measurement.measurementRequestH\x00\x12<\n\x10send_measurement\x18\r \x01(\x0b\x32 .SKF.Measurement.SendMeasurementH\x00\x12\'\n\x07\x63ommand\x18\x0e \x01(\x0b\x32\x14.SKF.command.CommandH\x00\x12\x1e\n\x03\x61\x63k\x18\x0f \x01(\x0b\x32\x0f.SKF.common.AckH\x00\x12\"\n\x05\x65rror\x18\x10 \x01(\x0b\x32\x11.SKF.common.ErrorH\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APP']._serialized_start=86
  _globals['_APP']._serialized_end=481
# @@protoc_insertion_point(module_scope)
