# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configuration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'configuration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfiguration.proto\x12\x11SKF.configuration\"\x12\n\x10\x43onfigurationElo\"z\n\x12send_configuration\x12\x1a\n\x12hash_configuration\x18\x01 \x01(\r\x12@\n\x11\x65lo_configuration\x18\x02 \x01(\x0b\x32#.SKF.configuration.ConfigurationEloH\x00\x42\x06\n\x04kindb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'configuration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGURATIONELO']._serialized_start=42
  _globals['_CONFIGURATIONELO']._serialized_end=60
  _globals['_SEND_CONFIGURATION']._serialized_start=62
  _globals['_SEND_CONFIGURATION']._serialized_end=184
# @@protoc_insertion_point(module_scope)
