# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fota.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfota.proto\x12\x08SKF.fota\"\x0c\n\nfota_start\"\x0c\n\nfota_slice\"\r\n\x0b\x66ota_verifyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOTA_START']._serialized_start=24
  _globals['_FOTA_START']._serialized_end=36
  _globals['_FOTA_SLICE']._serialized_start=38
  _globals['_FOTA_SLICE']._serialized_end=50
  _globals['_FOTA_VERIFY']._serialized_start=52
  _globals['_FOTA_VERIFY']._serialized_end=65
# @@protoc_insertion_point(module_scope)
