# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsession.proto\x12\x0bSKF.Session\"(\n\x0bOpenSession\x12\x19\n\x11\x63urrent_sync_time\x18\x01 \x01(\x04\"\x1f\n\x0fSessionInfo_ble\x12\x0c\n\x04rssi\x18\x01 \x01(\x11\"F\n\x10SessionInfo_mira\x12\x16\n\x0eparent_address\x18\x01 \x01(\x06\x12\x1a\n\x12parent_link_metric\x18\x02 \x01(\r\"\x8b\x01\n\x0bSessionInfo\x12\x38\n\x10session_info_ble\x18\x01 \x01(\x0b\x32\x1c.SKF.Session.SessionInfo_bleH\x00\x12:\n\x11session_info_mira\x18\x02 \x01(\x0b\x32\x1d.SKF.Session.SessionInfo_miraH\x00\x42\x06\n\x04kind\"\xb0\x02\n\rAcceptSession\x12\x12\n\nvirtual_id\x18\x01 \x01(\r\x12\x30\n\rhardware_type\x18\x02 \x01(\x0e\x32\x19.SKF.Session.HardwareType\x12\x12\n\nhw_version\x18\x03 \x01(\r\x12\x0e\n\x06serial\x18\x04 \x01(\x0c\x12\x12\n\nfw_version\x18\x05 \x01(\r\x12\x18\n\x10\x66w_cache_version\x18\x06 \x01(\r\x12\x13\n\x0b\x63onfig_hash\x18\x07 \x01(\r\x12\x11\n\tself_diag\x18\x08 \x01(\r\x12\x19\n\x11\x62\x61ttery_indicator\x18\t \x01(\r\x12\x33\n\x0csession_info\x18\n \x01(\x0b\x32\x18.SKF.Session.SessionInfoH\x00\x88\x01\x01\x42\x0f\n\r_session_info*\xa1\x01\n\x0cHardwareType\x12\x17\n\x13HardwareTypeUnknown\x10\x00\x12\x1c\n\x18HardwareTypeCmwa6120_std\x10\x01\x12\x1d\n\x19HardwareTypeCmwa6120_atex\x10\x02\x12\x1c\n\x18HardwareTypeCmwa6420_std\x10\x03\x12\x1d\n\x19HardwareTypeCmwa6420_atex\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HARDWARETYPE']._serialized_start=627
  _globals['_HARDWARETYPE']._serialized_end=788
  _globals['_OPENSESSION']._serialized_start=30
  _globals['_OPENSESSION']._serialized_end=70
  _globals['_SESSIONINFO_BLE']._serialized_start=72
  _globals['_SESSIONINFO_BLE']._serialized_end=103
  _globals['_SESSIONINFO_MIRA']._serialized_start=105
  _globals['_SESSIONINFO_MIRA']._serialized_end=175
  _globals['_SESSIONINFO']._serialized_start=178
  _globals['_SESSIONINFO']._serialized_end=317
  _globals['_ACCEPTSESSION']._serialized_start=320
  _globals['_ACCEPTSESSION']._serialized_end=624
# @@protoc_insertion_point(module_scope)
