/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKF_APP_APP_PB_H_INCLUDED
#define PB_SKF_APP_APP_PB_H_INCLUDED
#include <pb.h>
#include "session.pb.h"
#include "measurement.pb.h"
#include "command.pb.h"
#include "common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SKF_App_App {
    bool has_header;
    SKF_common_Header header;
    pb_size_t which_payload;
    union {
        SKF_Session_OpenSession open_session;
        SKF_Session_AcceptSession accept_session;
        SKF_Measurement_measurementRequest measurement_request;
        SKF_Measurement_SendMeasurement send_measurement;
        SKF_command_Command command;
        SKF_common_Ack ack;
        SKF_common_Error error;
    } payload;
} SKF_App_App;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SKF_App_App_init_default                 {false, SKF_common_Header_init_default, 0, {SKF_Session_OpenSession_init_default}}
#define SKF_App_App_init_zero                    {false, SKF_common_Header_init_zero, 0, {SKF_Session_OpenSession_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SKF_App_App_header_tag                   1
#define SKF_App_App_open_session_tag             10
#define SKF_App_App_accept_session_tag           11
#define SKF_App_App_measurement_request_tag      12
#define SKF_App_App_send_measurement_tag         13
#define SKF_App_App_command_tag                  14
#define SKF_App_App_ack_tag                      15
#define SKF_App_App_error_tag                    16

/* Struct field encoding specification for nanopb */
#define SKF_App_App_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,open_session,payload.open_session),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,accept_session,payload.accept_session),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,measurement_request,payload.measurement_request),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_measurement,payload.send_measurement),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command,payload.command),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,error,payload.error),  16)
#define SKF_App_App_CALLBACK NULL
#define SKF_App_App_DEFAULT NULL
#define SKF_App_App_header_MSGTYPE SKF_common_Header
#define SKF_App_App_payload_open_session_MSGTYPE SKF_Session_OpenSession
#define SKF_App_App_payload_accept_session_MSGTYPE SKF_Session_AcceptSession
#define SKF_App_App_payload_measurement_request_MSGTYPE SKF_Measurement_measurementRequest
#define SKF_App_App_payload_send_measurement_MSGTYPE SKF_Measurement_SendMeasurement
#define SKF_App_App_payload_command_MSGTYPE SKF_command_Command
#define SKF_App_App_payload_ack_MSGTYPE SKF_common_Ack
#define SKF_App_App_payload_error_MSGTYPE SKF_common_Error

extern const pb_msgdesc_t SKF_App_App_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKF_App_App_fields &SKF_App_App_msg

/* Maximum encoded size of messages (where known) */
#define SKF_APP_APP_PB_H_MAX_SIZE                SKF_App_App_size
#define SKF_App_App_size                         1228

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
