/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKF_COMMAND_COMMAND_PB_H_INCLUDED
#define PB_SKF_COMMAND_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SKF_command_CommandType {
    SKF_command_CommandType_CommandTypeUnknown = 0,
    SKF_command_CommandType_CommandTypeCloseSession = 1
} SKF_command_CommandType;

/* Struct definitions */
typedef struct _SKF_command_Command {
    SKF_command_CommandType command;
} SKF_command_Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SKF_command_CommandType_MIN SKF_command_CommandType_CommandTypeUnknown
#define _SKF_command_CommandType_MAX SKF_command_CommandType_CommandTypeCloseSession
#define _SKF_command_CommandType_ARRAYSIZE ((SKF_command_CommandType)(SKF_command_CommandType_CommandTypeCloseSession+1))

#define SKF_command_Command_command_ENUMTYPE SKF_command_CommandType


/* Initializer values for message structs */
#define SKF_command_Command_init_default         {_SKF_command_CommandType_MIN}
#define SKF_command_Command_init_zero            {_SKF_command_CommandType_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define SKF_command_Command_command_tag          1

/* Struct field encoding specification for nanopb */
#define SKF_command_Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1)
#define SKF_command_Command_CALLBACK NULL
#define SKF_command_Command_DEFAULT NULL

extern const pb_msgdesc_t SKF_command_Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKF_command_Command_fields &SKF_command_Command_msg

/* Maximum encoded size of messages (where known) */
#define SKF_COMMAND_COMMAND_PB_H_MAX_SIZE        SKF_command_Command_size
#define SKF_command_Command_size                 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
