/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKF_COMMON_COMMON_PB_H_INCLUDED
#define PB_SKF_COMMON_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SKF_common_Header {
    uint32_t version;
    uint32_t message_id; /* Message id is used to identify a message in case of request/answer */
    uint32_t current_fragment; /* Used if a message is on multiple frame */
    uint32_t total_fragments; /* Used if a message is on multiple frame */
} SKF_common_Header;

typedef struct _SKF_common_Ack {
    bool ack; /* true ACK, false NACK */
    uint32_t error_code; /* 0 means no error */
} SKF_common_Ack;

typedef struct _SKF_common_Error {
    uint32_t error_code;
} SKF_common_Error;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SKF_common_Header_init_default           {0, 0, 0, 0}
#define SKF_common_Ack_init_default              {0, 0}
#define SKF_common_Error_init_default            {0}
#define SKF_common_Header_init_zero              {0, 0, 0, 0}
#define SKF_common_Ack_init_zero                 {0, 0}
#define SKF_common_Error_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define SKF_common_Header_version_tag            1
#define SKF_common_Header_message_id_tag         2
#define SKF_common_Header_current_fragment_tag   4
#define SKF_common_Header_total_fragments_tag    5
#define SKF_common_Ack_ack_tag                   1
#define SKF_common_Ack_error_code_tag            2
#define SKF_common_Error_error_code_tag          1

/* Struct field encoding specification for nanopb */
#define SKF_common_Header_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, STATIC,   SINGULAR, UINT32,   message_id,        2) \
X(a, STATIC,   SINGULAR, UINT32,   current_fragment,   4) \
X(a, STATIC,   SINGULAR, UINT32,   total_fragments,   5)
#define SKF_common_Header_CALLBACK NULL
#define SKF_common_Header_DEFAULT NULL

#define SKF_common_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     ack,               1) \
X(a, STATIC,   SINGULAR, UINT32,   error_code,        2)
#define SKF_common_Ack_CALLBACK NULL
#define SKF_common_Ack_DEFAULT NULL

#define SKF_common_Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   error_code,        1)
#define SKF_common_Error_CALLBACK NULL
#define SKF_common_Error_DEFAULT NULL

extern const pb_msgdesc_t SKF_common_Header_msg;
extern const pb_msgdesc_t SKF_common_Ack_msg;
extern const pb_msgdesc_t SKF_common_Error_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKF_common_Header_fields &SKF_common_Header_msg
#define SKF_common_Ack_fields &SKF_common_Ack_msg
#define SKF_common_Error_fields &SKF_common_Error_msg

/* Maximum encoded size of messages (where known) */
#define SKF_COMMON_COMMON_PB_H_MAX_SIZE          SKF_common_Header_size
#define SKF_common_Ack_size                      8
#define SKF_common_Error_size                    6
#define SKF_common_Header_size                   24

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
