/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKF_CONFIGURATION_CONFIGURATION_PB_H_INCLUDED
#define PB_SKF_CONFIGURATION_CONFIGURATION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SKF_configuration_ConfigurationElo {
    char dummy_field;
} SKF_configuration_ConfigurationElo;

typedef struct _SKF_configuration_send_configuration {
    uint32_t hash_configuration;
    pb_size_t which_kind;
    union {
        SKF_configuration_ConfigurationElo elo_configuration;
    } kind;
} SKF_configuration_send_configuration;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SKF_configuration_ConfigurationElo_init_default {0}
#define SKF_configuration_send_configuration_init_default {0, 0, {SKF_configuration_ConfigurationElo_init_default}}
#define SKF_configuration_ConfigurationElo_init_zero {0}
#define SKF_configuration_send_configuration_init_zero {0, 0, {SKF_configuration_ConfigurationElo_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SKF_configuration_send_configuration_hash_configuration_tag 1
#define SKF_configuration_send_configuration_elo_configuration_tag 2

/* Struct field encoding specification for nanopb */
#define SKF_configuration_ConfigurationElo_FIELDLIST(X, a) \

#define SKF_configuration_ConfigurationElo_CALLBACK NULL
#define SKF_configuration_ConfigurationElo_DEFAULT NULL

#define SKF_configuration_send_configuration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   hash_configuration,   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,elo_configuration,kind.elo_configuration),   2)
#define SKF_configuration_send_configuration_CALLBACK NULL
#define SKF_configuration_send_configuration_DEFAULT NULL
#define SKF_configuration_send_configuration_kind_elo_configuration_MSGTYPE SKF_configuration_ConfigurationElo

extern const pb_msgdesc_t SKF_configuration_ConfigurationElo_msg;
extern const pb_msgdesc_t SKF_configuration_send_configuration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKF_configuration_ConfigurationElo_fields &SKF_configuration_ConfigurationElo_msg
#define SKF_configuration_send_configuration_fields &SKF_configuration_send_configuration_msg

/* Maximum encoded size of messages (where known) */
#define SKF_CONFIGURATION_CONFIGURATION_PB_H_MAX_SIZE SKF_configuration_send_configuration_size
#define SKF_configuration_ConfigurationElo_size  0
#define SKF_configuration_send_configuration_size 8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
