/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKF_FOTA_FOTA_PB_H_INCLUDED
#define PB_SKF_FOTA_FOTA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SKF_fota_fota_start {
    char dummy_field;
} SKF_fota_fota_start;

typedef struct _SKF_fota_fota_slice {
    char dummy_field;
} SKF_fota_fota_slice;

typedef struct _SKF_fota_fota_verify {
    char dummy_field;
} SKF_fota_fota_verify;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SKF_fota_fota_start_init_default         {0}
#define SKF_fota_fota_slice_init_default         {0}
#define SKF_fota_fota_verify_init_default        {0}
#define SKF_fota_fota_start_init_zero            {0}
#define SKF_fota_fota_slice_init_zero            {0}
#define SKF_fota_fota_verify_init_zero           {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
#define SKF_fota_fota_start_FIELDLIST(X, a) \

#define SKF_fota_fota_start_CALLBACK NULL
#define SKF_fota_fota_start_DEFAULT NULL

#define SKF_fota_fota_slice_FIELDLIST(X, a) \

#define SKF_fota_fota_slice_CALLBACK NULL
#define SKF_fota_fota_slice_DEFAULT NULL

#define SKF_fota_fota_verify_FIELDLIST(X, a) \

#define SKF_fota_fota_verify_CALLBACK NULL
#define SKF_fota_fota_verify_DEFAULT NULL

extern const pb_msgdesc_t SKF_fota_fota_start_msg;
extern const pb_msgdesc_t SKF_fota_fota_slice_msg;
extern const pb_msgdesc_t SKF_fota_fota_verify_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKF_fota_fota_start_fields &SKF_fota_fota_start_msg
#define SKF_fota_fota_slice_fields &SKF_fota_fota_slice_msg
#define SKF_fota_fota_verify_fields &SKF_fota_fota_verify_msg

/* Maximum encoded size of messages (where known) */
#define SKF_FOTA_FOTA_PB_H_MAX_SIZE              SKF_fota_fota_start_size
#define SKF_fota_fota_slice_size                 0
#define SKF_fota_fota_start_size                 0
#define SKF_fota_fota_verify_size                0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
