/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "fota.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SKF_fota_fota_start, SKF_fota_fota_start, AUTO)


PB_BIND(SKF_fota_fota_slice, SKF_fota_fota_slice, AUTO)


PB_BIND(SKF_fota_fota_verify, SKF_fota_fota_verify, AUTO)



