/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "measurement.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SKF_Measurement_measurementType, SKF_Measurement_measurementType, AUTO)


PB_BIND(SKF_Measurement_measurementRequest, SKF_Measurement_measurementRequest, AUTO)


PB_BIND(SKF_Measurement_MetadataElo, SKF_Measurement_MetadataElo, AUTO)


PB_BIND(SKF_Measurement_Metadata, SKF_Measurement_Metadata, AUTO)


PB_BIND(SKF_Measurement_MetadataEloTwf, SKF_Measurement_MetadataEloTwf, AUTO)


PB_BIND(SKF_Measurement_MetadataTwf, SKF_Measurement_MetadataTwf, AUTO)


PB_BIND(SKF_Measurement_MeasurementOveralls, SKF_Measurement_MeasurementOveralls, AUTO)


PB_BIND(SKF_Measurement_MeasurementDataContent, SKF_Measurement_MeasurementDataContent, 2)


PB_BIND(SKF_Measurement_MeasurementData, SKF_Measurement_MeasurementData, 2)


PB_BIND(SKF_Measurement_CommonMetaData, SKF_Measurement_CommonMetaData, AUTO)


PB_BIND(SKF_Measurement_SendMeasurement, SKF_Measurement_SendMeasurement, 2)







