/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKF_MEASUREMENT_MEASUREMENT_PB_H_INCLUDED
#define PB_SKF_MEASUREMENT_MEASUREMENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SKF_Measurement_MeasurementType {
    SKF_Measurement_MeasurementType_MeasurementTypeUnknown = 0,
    /* overall */
    SKF_Measurement_MeasurementType_MeasurementTypeAccelerationOverall = 1,
    SKF_Measurement_MeasurementType_MeasurementTypeVelocityOverall = 2,
    SKF_Measurement_MeasurementType_MeasurementTypeEnveloper3Overall = 3,
    SKF_Measurement_MeasurementType_MeasurementTypeTemperatureOverall = 4,
    /* twf */
    SKF_Measurement_MeasurementType_MeasurementTypeAccelerationTwf = 5,
    SKF_Measurement_MeasurementType_MeasurementTypeVelocityTwf = 6,
    SKF_Measurement_MeasurementType_MeasurementTypeEnveloper3Twf = 7
} SKF_Measurement_MeasurementType;

typedef enum _SKF_Measurement_DataType {
    SKF_Measurement_DataType_Unknown = 0,
    SKF_Measurement_DataType_U8 = 1,
    SKF_Measurement_DataType_S8 = 2,
    SKF_Measurement_DataType_U16 = 3,
    SKF_Measurement_DataType_S16 = 4,
    SKF_Measurement_DataType_U32 = 5,
    SKF_Measurement_DataType_S32 = 6,
    SKF_Measurement_DataType_F32 = 7
} SKF_Measurement_DataType;

/* Struct definitions */
typedef struct _SKF_Measurement_measurementType {
    SKF_Measurement_MeasurementType measurement_type;
} SKF_Measurement_measurementType;

typedef struct _SKF_Measurement_measurementRequest {
    pb_size_t measurement_count;
    SKF_Measurement_measurementType measurement[4];
} SKF_Measurement_measurementRequest;

typedef struct _SKF_Measurement_MetadataElo {
    SKF_Measurement_MeasurementType vibration_path;
    uint32_t duration;
} SKF_Measurement_MetadataElo;

/* create a over load message for future */
typedef struct _SKF_Measurement_Metadata {
    pb_size_t which_kind;
    union {
        SKF_Measurement_MetadataElo elo_metadata;
    } kind;
} SKF_Measurement_Metadata;

typedef struct _SKF_Measurement_MetadataEloTwf {
    uint32_t twf_hash;
    uint32_t sampling_rate;
    SKF_Measurement_DataType data_type;
} SKF_Measurement_MetadataEloTwf;

typedef struct _SKF_Measurement_MetadataTwf {
    pb_size_t which_kind;
    union {
        SKF_Measurement_MetadataEloTwf elo_metadata_twf;
    } kind;
} SKF_Measurement_MetadataTwf;

typedef struct _SKF_Measurement_MeasurementOveralls {
    uint32_t peak2peak;
    uint32_t rms;
    uint32_t peak;
    uint32_t std;
    int32_t mean;
} SKF_Measurement_MeasurementOveralls;

typedef PB_BYTES_ARRAY_T(256) SKF_Measurement_MeasurementDataContent_data_bytes_t;
typedef struct _SKF_Measurement_MeasurementDataContent {
    pb_size_t which_kind;
    union {
        SKF_Measurement_MeasurementDataContent_data_bytes_t data_bytes;
        int32_t int32_data;
        SKF_Measurement_MeasurementOveralls measurement_overall;
    } kind;
} SKF_Measurement_MeasurementDataContent;

/* Measurement is compose of specific metadata and data */
typedef struct _SKF_Measurement_MeasurementData {
    bool has_metadata;
    SKF_Measurement_Metadata metadata;
    bool has_metadata_twf;
    SKF_Measurement_MetadataTwf metadata_twf;
    bool has_data;
    SKF_Measurement_MeasurementDataContent data;
} SKF_Measurement_MeasurementData;

typedef struct _SKF_Measurement_CommonMetaData {
    /* Unix time (seconds) */
    uint64_t time;
    /* Hash of the configuration used for measurement */
    uint32_t config_hash;
} SKF_Measurement_CommonMetaData;

typedef struct _SKF_Measurement_SendMeasurement {
    bool has_common_meta_data;
    SKF_Measurement_CommonMetaData common_meta_data;
    pb_size_t measurement_data_count;
    SKF_Measurement_MeasurementData measurement_data[4];
} SKF_Measurement_SendMeasurement;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SKF_Measurement_MeasurementType_MIN SKF_Measurement_MeasurementType_MeasurementTypeUnknown
#define _SKF_Measurement_MeasurementType_MAX SKF_Measurement_MeasurementType_MeasurementTypeEnveloper3Twf
#define _SKF_Measurement_MeasurementType_ARRAYSIZE ((SKF_Measurement_MeasurementType)(SKF_Measurement_MeasurementType_MeasurementTypeEnveloper3Twf+1))

#define _SKF_Measurement_DataType_MIN SKF_Measurement_DataType_Unknown
#define _SKF_Measurement_DataType_MAX SKF_Measurement_DataType_F32
#define _SKF_Measurement_DataType_ARRAYSIZE ((SKF_Measurement_DataType)(SKF_Measurement_DataType_F32+1))

#define SKF_Measurement_measurementType_measurement_type_ENUMTYPE SKF_Measurement_MeasurementType


#define SKF_Measurement_MetadataElo_vibration_path_ENUMTYPE SKF_Measurement_MeasurementType


#define SKF_Measurement_MetadataEloTwf_data_type_ENUMTYPE SKF_Measurement_DataType








/* Initializer values for message structs */
#define SKF_Measurement_measurementType_init_default {_SKF_Measurement_MeasurementType_MIN}
#define SKF_Measurement_measurementRequest_init_default {0, {SKF_Measurement_measurementType_init_default, SKF_Measurement_measurementType_init_default, SKF_Measurement_measurementType_init_default, SKF_Measurement_measurementType_init_default}}
#define SKF_Measurement_MetadataElo_init_default {_SKF_Measurement_MeasurementType_MIN, 0}
#define SKF_Measurement_Metadata_init_default    {0, {SKF_Measurement_MetadataElo_init_default}}
#define SKF_Measurement_MetadataEloTwf_init_default {0, 0, _SKF_Measurement_DataType_MIN}
#define SKF_Measurement_MetadataTwf_init_default {0, {SKF_Measurement_MetadataEloTwf_init_default}}
#define SKF_Measurement_MeasurementOveralls_init_default {0, 0, 0, 0, 0}
#define SKF_Measurement_MeasurementDataContent_init_default {0, {{0, {0}}}}
#define SKF_Measurement_MeasurementData_init_default {false, SKF_Measurement_Metadata_init_default, false, SKF_Measurement_MetadataTwf_init_default, false, SKF_Measurement_MeasurementDataContent_init_default}
#define SKF_Measurement_CommonMetaData_init_default {0, 0}
#define SKF_Measurement_SendMeasurement_init_default {false, SKF_Measurement_CommonMetaData_init_default, 0, {SKF_Measurement_MeasurementData_init_default, SKF_Measurement_MeasurementData_init_default, SKF_Measurement_MeasurementData_init_default, SKF_Measurement_MeasurementData_init_default}}
#define SKF_Measurement_measurementType_init_zero {_SKF_Measurement_MeasurementType_MIN}
#define SKF_Measurement_measurementRequest_init_zero {0, {SKF_Measurement_measurementType_init_zero, SKF_Measurement_measurementType_init_zero, SKF_Measurement_measurementType_init_zero, SKF_Measurement_measurementType_init_zero}}
#define SKF_Measurement_MetadataElo_init_zero    {_SKF_Measurement_MeasurementType_MIN, 0}
#define SKF_Measurement_Metadata_init_zero       {0, {SKF_Measurement_MetadataElo_init_zero}}
#define SKF_Measurement_MetadataEloTwf_init_zero {0, 0, _SKF_Measurement_DataType_MIN}
#define SKF_Measurement_MetadataTwf_init_zero    {0, {SKF_Measurement_MetadataEloTwf_init_zero}}
#define SKF_Measurement_MeasurementOveralls_init_zero {0, 0, 0, 0, 0}
#define SKF_Measurement_MeasurementDataContent_init_zero {0, {{0, {0}}}}
#define SKF_Measurement_MeasurementData_init_zero {false, SKF_Measurement_Metadata_init_zero, false, SKF_Measurement_MetadataTwf_init_zero, false, SKF_Measurement_MeasurementDataContent_init_zero}
#define SKF_Measurement_CommonMetaData_init_zero {0, 0}
#define SKF_Measurement_SendMeasurement_init_zero {false, SKF_Measurement_CommonMetaData_init_zero, 0, {SKF_Measurement_MeasurementData_init_zero, SKF_Measurement_MeasurementData_init_zero, SKF_Measurement_MeasurementData_init_zero, SKF_Measurement_MeasurementData_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SKF_Measurement_measurementType_measurement_type_tag 1
#define SKF_Measurement_measurementRequest_measurement_tag 1
#define SKF_Measurement_MetadataElo_vibration_path_tag 1
#define SKF_Measurement_MetadataElo_duration_tag 3
#define SKF_Measurement_Metadata_elo_metadata_tag 1
#define SKF_Measurement_MetadataEloTwf_twf_hash_tag 1
#define SKF_Measurement_MetadataEloTwf_sampling_rate_tag 2
#define SKF_Measurement_MetadataEloTwf_data_type_tag 3
#define SKF_Measurement_MetadataTwf_elo_metadata_twf_tag 1
#define SKF_Measurement_MeasurementOveralls_peak2peak_tag 1
#define SKF_Measurement_MeasurementOveralls_rms_tag 2
#define SKF_Measurement_MeasurementOveralls_peak_tag 3
#define SKF_Measurement_MeasurementOveralls_std_tag 4
#define SKF_Measurement_MeasurementOveralls_mean_tag 5
#define SKF_Measurement_MeasurementDataContent_data_bytes_tag 1
#define SKF_Measurement_MeasurementDataContent_int32_data_tag 2
#define SKF_Measurement_MeasurementDataContent_measurement_overall_tag 3
#define SKF_Measurement_MeasurementData_metadata_tag 1
#define SKF_Measurement_MeasurementData_metadata_twf_tag 2
#define SKF_Measurement_MeasurementData_data_tag 3
#define SKF_Measurement_CommonMetaData_time_tag  1
#define SKF_Measurement_CommonMetaData_config_hash_tag 2
#define SKF_Measurement_SendMeasurement_common_meta_data_tag 1
#define SKF_Measurement_SendMeasurement_measurement_data_tag 2

/* Struct field encoding specification for nanopb */
#define SKF_Measurement_measurementType_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    measurement_type,   1)
#define SKF_Measurement_measurementType_CALLBACK NULL
#define SKF_Measurement_measurementType_DEFAULT NULL

#define SKF_Measurement_measurementRequest_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  measurement,       1)
#define SKF_Measurement_measurementRequest_CALLBACK NULL
#define SKF_Measurement_measurementRequest_DEFAULT NULL
#define SKF_Measurement_measurementRequest_measurement_MSGTYPE SKF_Measurement_measurementType

#define SKF_Measurement_MetadataElo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    vibration_path,    1) \
X(a, STATIC,   SINGULAR, UINT32,   duration,          3)
#define SKF_Measurement_MetadataElo_CALLBACK NULL
#define SKF_Measurement_MetadataElo_DEFAULT NULL

#define SKF_Measurement_Metadata_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,elo_metadata,kind.elo_metadata),   1)
#define SKF_Measurement_Metadata_CALLBACK NULL
#define SKF_Measurement_Metadata_DEFAULT NULL
#define SKF_Measurement_Metadata_kind_elo_metadata_MSGTYPE SKF_Measurement_MetadataElo

#define SKF_Measurement_MetadataEloTwf_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   twf_hash,          1) \
X(a, STATIC,   SINGULAR, UINT32,   sampling_rate,     2) \
X(a, STATIC,   SINGULAR, UENUM,    data_type,         3)
#define SKF_Measurement_MetadataEloTwf_CALLBACK NULL
#define SKF_Measurement_MetadataEloTwf_DEFAULT NULL

#define SKF_Measurement_MetadataTwf_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,elo_metadata_twf,kind.elo_metadata_twf),   1)
#define SKF_Measurement_MetadataTwf_CALLBACK NULL
#define SKF_Measurement_MetadataTwf_DEFAULT NULL
#define SKF_Measurement_MetadataTwf_kind_elo_metadata_twf_MSGTYPE SKF_Measurement_MetadataEloTwf

#define SKF_Measurement_MeasurementOveralls_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   peak2peak,         1) \
X(a, STATIC,   SINGULAR, UINT32,   rms,               2) \
X(a, STATIC,   SINGULAR, UINT32,   peak,              3) \
X(a, STATIC,   SINGULAR, UINT32,   std,               4) \
X(a, STATIC,   SINGULAR, SINT32,   mean,              5)
#define SKF_Measurement_MeasurementOveralls_CALLBACK NULL
#define SKF_Measurement_MeasurementOveralls_DEFAULT NULL

#define SKF_Measurement_MeasurementDataContent_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    BYTES,    (kind,data_bytes,kind.data_bytes),   1) \
X(a, STATIC,   ONEOF,    INT32,    (kind,int32_data,kind.int32_data),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,measurement_overall,kind.measurement_overall),   3)
#define SKF_Measurement_MeasurementDataContent_CALLBACK NULL
#define SKF_Measurement_MeasurementDataContent_DEFAULT NULL
#define SKF_Measurement_MeasurementDataContent_kind_measurement_overall_MSGTYPE SKF_Measurement_MeasurementOveralls

#define SKF_Measurement_MeasurementData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata,          1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  metadata_twf,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  data,              3)
#define SKF_Measurement_MeasurementData_CALLBACK NULL
#define SKF_Measurement_MeasurementData_DEFAULT NULL
#define SKF_Measurement_MeasurementData_metadata_MSGTYPE SKF_Measurement_Metadata
#define SKF_Measurement_MeasurementData_metadata_twf_MSGTYPE SKF_Measurement_MetadataTwf
#define SKF_Measurement_MeasurementData_data_MSGTYPE SKF_Measurement_MeasurementDataContent

#define SKF_Measurement_CommonMetaData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   time,              1) \
X(a, STATIC,   SINGULAR, UINT32,   config_hash,       2)
#define SKF_Measurement_CommonMetaData_CALLBACK NULL
#define SKF_Measurement_CommonMetaData_DEFAULT NULL

#define SKF_Measurement_SendMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  common_meta_data,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  measurement_data,   2)
#define SKF_Measurement_SendMeasurement_CALLBACK NULL
#define SKF_Measurement_SendMeasurement_DEFAULT NULL
#define SKF_Measurement_SendMeasurement_common_meta_data_MSGTYPE SKF_Measurement_CommonMetaData
#define SKF_Measurement_SendMeasurement_measurement_data_MSGTYPE SKF_Measurement_MeasurementData

extern const pb_msgdesc_t SKF_Measurement_measurementType_msg;
extern const pb_msgdesc_t SKF_Measurement_measurementRequest_msg;
extern const pb_msgdesc_t SKF_Measurement_MetadataElo_msg;
extern const pb_msgdesc_t SKF_Measurement_Metadata_msg;
extern const pb_msgdesc_t SKF_Measurement_MetadataEloTwf_msg;
extern const pb_msgdesc_t SKF_Measurement_MetadataTwf_msg;
extern const pb_msgdesc_t SKF_Measurement_MeasurementOveralls_msg;
extern const pb_msgdesc_t SKF_Measurement_MeasurementDataContent_msg;
extern const pb_msgdesc_t SKF_Measurement_MeasurementData_msg;
extern const pb_msgdesc_t SKF_Measurement_CommonMetaData_msg;
extern const pb_msgdesc_t SKF_Measurement_SendMeasurement_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKF_Measurement_measurementType_fields &SKF_Measurement_measurementType_msg
#define SKF_Measurement_measurementRequest_fields &SKF_Measurement_measurementRequest_msg
#define SKF_Measurement_MetadataElo_fields &SKF_Measurement_MetadataElo_msg
#define SKF_Measurement_Metadata_fields &SKF_Measurement_Metadata_msg
#define SKF_Measurement_MetadataEloTwf_fields &SKF_Measurement_MetadataEloTwf_msg
#define SKF_Measurement_MetadataTwf_fields &SKF_Measurement_MetadataTwf_msg
#define SKF_Measurement_MeasurementOveralls_fields &SKF_Measurement_MeasurementOveralls_msg
#define SKF_Measurement_MeasurementDataContent_fields &SKF_Measurement_MeasurementDataContent_msg
#define SKF_Measurement_MeasurementData_fields &SKF_Measurement_MeasurementData_msg
#define SKF_Measurement_CommonMetaData_fields &SKF_Measurement_CommonMetaData_msg
#define SKF_Measurement_SendMeasurement_fields &SKF_Measurement_SendMeasurement_msg

/* Maximum encoded size of messages (where known) */
#define SKF_MEASUREMENT_MEASUREMENT_PB_H_MAX_SIZE SKF_Measurement_SendMeasurement_size
#define SKF_Measurement_CommonMetaData_size      17
#define SKF_Measurement_MeasurementDataContent_size 259
#define SKF_Measurement_MeasurementData_size     292
#define SKF_Measurement_MeasurementOveralls_size 30
#define SKF_Measurement_MetadataEloTwf_size      14
#define SKF_Measurement_MetadataElo_size         8
#define SKF_Measurement_MetadataTwf_size         16
#define SKF_Measurement_Metadata_size            10
#define SKF_Measurement_SendMeasurement_size     1199
#define SKF_Measurement_measurementRequest_size  16
#define SKF_Measurement_measurementType_size     2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
