/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SKF_SESSION_SESSION_PB_H_INCLUDED
#define PB_SKF_SESSION_SESSION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _SKF_Session_HardwareType {
    SKF_Session_HardwareType_HardwareTypeUnknown = 0,
    SKF_Session_HardwareType_HardwareTypeCmwa6120_std = 1,
    SKF_Session_HardwareType_HardwareTypeCmwa6120_atex = 2,
    SKF_Session_HardwareType_HardwareTypeCmwa6420_std = 3,
    SKF_Session_HardwareType_HardwareTypeCmwa6420_atex = 4
} SKF_Session_HardwareType;

/* Struct definitions */
/* GW send OpenSession, sensor answer with AcceptSession */
typedef struct _SKF_Session_OpenSession {
    uint64_t current_sync_time; /* Unix time (seconds) */
} SKF_Session_OpenSession;

typedef struct _SKF_Session_SessionInfo_ble {
    int32_t rssi;
} SKF_Session_SessionInfo_ble;

typedef struct _SKF_Session_SessionInfo_mira {
    uint64_t parent_address;
    uint32_t parent_link_metric;
} SKF_Session_SessionInfo_mira;

typedef struct _SKF_Session_SessionInfo {
    pb_size_t which_kind;
    union {
        SKF_Session_SessionInfo_ble session_info_ble;
        SKF_Session_SessionInfo_mira session_info_mira;
    } kind;
} SKF_Session_SessionInfo;

typedef PB_BYTES_ARRAY_T(6) SKF_Session_AcceptSession_serial_t;
typedef struct _SKF_Session_AcceptSession {
    uint32_t virtual_id;
    SKF_Session_HardwareType hardware_type;
    uint32_t hw_version;
    SKF_Session_AcceptSession_serial_t serial;
    uint32_t fw_version;
    uint32_t fw_cache_version;
    uint32_t config_hash;
    uint32_t self_diag;
    uint32_t battery_indicator;
    bool has_session_info;
    SKF_Session_SessionInfo session_info;
} SKF_Session_AcceptSession;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SKF_Session_HardwareType_MIN SKF_Session_HardwareType_HardwareTypeUnknown
#define _SKF_Session_HardwareType_MAX SKF_Session_HardwareType_HardwareTypeCmwa6420_atex
#define _SKF_Session_HardwareType_ARRAYSIZE ((SKF_Session_HardwareType)(SKF_Session_HardwareType_HardwareTypeCmwa6420_atex+1))





#define SKF_Session_AcceptSession_hardware_type_ENUMTYPE SKF_Session_HardwareType


/* Initializer values for message structs */
#define SKF_Session_OpenSession_init_default     {0}
#define SKF_Session_SessionInfo_ble_init_default {0}
#define SKF_Session_SessionInfo_mira_init_default {0, 0}
#define SKF_Session_SessionInfo_init_default     {0, {SKF_Session_SessionInfo_ble_init_default}}
#define SKF_Session_AcceptSession_init_default   {0, _SKF_Session_HardwareType_MIN, 0, {0, {0}}, 0, 0, 0, 0, 0, false, SKF_Session_SessionInfo_init_default}
#define SKF_Session_OpenSession_init_zero        {0}
#define SKF_Session_SessionInfo_ble_init_zero    {0}
#define SKF_Session_SessionInfo_mira_init_zero   {0, 0}
#define SKF_Session_SessionInfo_init_zero        {0, {SKF_Session_SessionInfo_ble_init_zero}}
#define SKF_Session_AcceptSession_init_zero      {0, _SKF_Session_HardwareType_MIN, 0, {0, {0}}, 0, 0, 0, 0, 0, false, SKF_Session_SessionInfo_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define SKF_Session_OpenSession_current_sync_time_tag 1
#define SKF_Session_SessionInfo_ble_rssi_tag     1
#define SKF_Session_SessionInfo_mira_parent_address_tag 1
#define SKF_Session_SessionInfo_mira_parent_link_metric_tag 2
#define SKF_Session_SessionInfo_session_info_ble_tag 1
#define SKF_Session_SessionInfo_session_info_mira_tag 2
#define SKF_Session_AcceptSession_virtual_id_tag 1
#define SKF_Session_AcceptSession_hardware_type_tag 2
#define SKF_Session_AcceptSession_hw_version_tag 3
#define SKF_Session_AcceptSession_serial_tag     4
#define SKF_Session_AcceptSession_fw_version_tag 5
#define SKF_Session_AcceptSession_fw_cache_version_tag 6
#define SKF_Session_AcceptSession_config_hash_tag 7
#define SKF_Session_AcceptSession_self_diag_tag  8
#define SKF_Session_AcceptSession_battery_indicator_tag 9
#define SKF_Session_AcceptSession_session_info_tag 10

/* Struct field encoding specification for nanopb */
#define SKF_Session_OpenSession_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   current_sync_time,   1)
#define SKF_Session_OpenSession_CALLBACK NULL
#define SKF_Session_OpenSession_DEFAULT NULL

#define SKF_Session_SessionInfo_ble_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              1)
#define SKF_Session_SessionInfo_ble_CALLBACK NULL
#define SKF_Session_SessionInfo_ble_DEFAULT NULL

#define SKF_Session_SessionInfo_mira_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED64,  parent_address,    1) \
X(a, STATIC,   SINGULAR, UINT32,   parent_link_metric,   2)
#define SKF_Session_SessionInfo_mira_CALLBACK NULL
#define SKF_Session_SessionInfo_mira_DEFAULT NULL

#define SKF_Session_SessionInfo_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,session_info_ble,kind.session_info_ble),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,session_info_mira,kind.session_info_mira),   2)
#define SKF_Session_SessionInfo_CALLBACK NULL
#define SKF_Session_SessionInfo_DEFAULT NULL
#define SKF_Session_SessionInfo_kind_session_info_ble_MSGTYPE SKF_Session_SessionInfo_ble
#define SKF_Session_SessionInfo_kind_session_info_mira_MSGTYPE SKF_Session_SessionInfo_mira

#define SKF_Session_AcceptSession_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   virtual_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    hardware_type,     2) \
X(a, STATIC,   SINGULAR, UINT32,   hw_version,        3) \
X(a, STATIC,   SINGULAR, BYTES,    serial,            4) \
X(a, STATIC,   SINGULAR, UINT32,   fw_version,        5) \
X(a, STATIC,   SINGULAR, UINT32,   fw_cache_version,   6) \
X(a, STATIC,   SINGULAR, UINT32,   config_hash,       7) \
X(a, STATIC,   SINGULAR, UINT32,   self_diag,         8) \
X(a, STATIC,   SINGULAR, UINT32,   battery_indicator,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  session_info,     10)
#define SKF_Session_AcceptSession_CALLBACK NULL
#define SKF_Session_AcceptSession_DEFAULT NULL
#define SKF_Session_AcceptSession_session_info_MSGTYPE SKF_Session_SessionInfo

extern const pb_msgdesc_t SKF_Session_OpenSession_msg;
extern const pb_msgdesc_t SKF_Session_SessionInfo_ble_msg;
extern const pb_msgdesc_t SKF_Session_SessionInfo_mira_msg;
extern const pb_msgdesc_t SKF_Session_SessionInfo_msg;
extern const pb_msgdesc_t SKF_Session_AcceptSession_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKF_Session_OpenSession_fields &SKF_Session_OpenSession_msg
#define SKF_Session_SessionInfo_ble_fields &SKF_Session_SessionInfo_ble_msg
#define SKF_Session_SessionInfo_mira_fields &SKF_Session_SessionInfo_mira_msg
#define SKF_Session_SessionInfo_fields &SKF_Session_SessionInfo_msg
#define SKF_Session_AcceptSession_fields &SKF_Session_AcceptSession_msg

/* Maximum encoded size of messages (where known) */
#define SKF_SESSION_SESSION_PB_H_MAX_SIZE        SKF_Session_AcceptSession_size
#define SKF_Session_AcceptSession_size           71
#define SKF_Session_OpenSession_size             11
#define SKF_Session_SessionInfo_ble_size         6
#define SKF_Session_SessionInfo_mira_size        15
#define SKF_Session_SessionInfo_size             17

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
