/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "session.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SKF_Session_OpenSession, SKF_Session_OpenSession, AUTO)


PB_BIND(SKF_Session_SessionInfo_ble, SKF_Session_SessionInfo_ble, AUTO)


PB_BIND(SKF_Session_SessionInfo_mira, SKF_Session_SessionInfo_mira, AUTO)


PB_BIND(SKF_Session_SessionInfo, SKF_Session_SessionInfo, AUTO)


PB_BIND(SKF_Session_AcceptSession, SKF_Session_AcceptSession, AUTO)





