# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Debug.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'Debug.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2
import Froto_pb2 as Froto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x44\x65\x62ug.proto\x12\x0eSKFChina.Debug\x1a\x0c\x43ommon.proto\x1a\x0b\x46roto.proto\"H\n\x11\x44\x65\x62ugMsgUniversal\x12\x11\n\x04time\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x17\n\x0fmessage_content\x18\x02 \x01(\x0c\x42\x07\n\x05_time\"T\n\x0b\x44\x65\x62ugMetric\x12\x11\n\x04time\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x10\n\x08MetricId\x18\x02 \x01(\r\x12\x17\n\x0fmessage_content\x18\x03 \x01(\x0c\x42\x07\n\x05_time\"\xa8\x02\n\x0c\x44\x65\x62ugMessage\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.SKFChina.Froto.FrotoHeader\x12\x0e\n\x06\x61ppVer\x18\x02 \x01(\r\x12\x11\n\tsensor_id\x18\x03 \x01(\x0c\x12-\n\x07product\x18\x04 \x01(\x0e\x32\x1c.SKFChina.Common.ProductType\x12\x1a\n\ris_big_endian\x18\x05 \x01(\x08H\x00\x88\x01\x01\x12\x38\n\rdebug_message\x18\x06 \x03(\x0b\x32!.SKFChina.Debug.DebugMsgUniversal\x12\x31\n\x0c\x64\x65\x62ug_metric\x18\x07 \x03(\x0b\x32\x1b.SKFChina.Debug.DebugMetricB\x10\n\x0e_is_big_endianb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Debug_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEBUGMSGUNIVERSAL']._serialized_start=58
  _globals['_DEBUGMSGUNIVERSAL']._serialized_end=130
  _globals['_DEBUGMETRIC']._serialized_start=132
  _globals['_DEBUGMETRIC']._serialized_end=216
  _globals['_DEBUGMESSAGE']._serialized_start=219
  _globals['_DEBUGMESSAGE']._serialized_end=515
# @@protoc_insertion_point(module_scope)
